# Generated by Django 3.1.6 on 2021-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('S.Y.Engineering', 'S.Y.Engineering'), ('F.Y.Engineering', 'F.Y.Engineering'), ('other', 'other')], default='other', max_length=120),
        ),
    ]
