# Generated by Django 3.1.6 on 2021-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210424_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('S.Y.Engineering', 'S.Y.Engineering'), ('Comic', 'Comic'), ('other', 'other'), ('F.Y.Engineering', 'F.Y.Engineering'), ('Science Fiction', 'Science Fiction')], default='other', max_length=120),
        ),
    ]
