# Generated by Django 3.1.6 on 2021-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210424_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('other', 'other'), ('Science Fiction', 'Science Fiction'), ('S.Y.Engineering', 'S.Y.Engineering'), ('Comic', 'Comic'), ('F.Y.Engineering', 'F.Y.Engineering')], default='other', max_length=120),
        ),
    ]
