# Generated by Django 3.1.6 on 2021-06-02 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210427_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('S.Y.Engineering', 'S.Y.Engineering'), ('other', 'other'), ('Comic', 'Comic'), ('F.Y.Engineering', 'F.Y.Engineering'), ('Science Fiction', 'Science Fiction')], default='other', max_length=120),
        ),
    ]
