# Generated by Django 3.1.6 on 2021-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210602_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Science Fiction', 'Science Fiction'), ('S.Y.Engineering', 'S.Y.Engineering'), ('Horror', 'Horror'), ('Comic', 'Comic'), ('F.Y.Engineering', 'F.Y.Engineering'), ('other', 'other')], default='other', max_length=120),
        ),
    ]
