# Generated by Django 3.1.6 on 2021-07-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210703_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Science Fiction', 'Science Fiction'), ('S.Y.Engineering', 'S.Y.Engineering'), ('Horror', 'Horror'), ('Comic', 'Comic'), ('other', 'other'), ('F.Y.Engineering', 'F.Y.Engineering')], default='other', max_length=120),
        ),
    ]
