# Generated by Django 3.1.6 on 2021-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210707_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('S.Y.Engineering', 'S.Y.Engineering'), ('other', 'other'), ('F.Y.Engineering', 'F.Y.Engineering'), ('Science Fiction', 'Science Fiction'), ('Comic', 'Comic'), ('Horror', 'Horror')], default='other', max_length=120),
        ),
    ]
