# Generated by Django 3.1.4 on 2021-09-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210724_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Science Fiction', 'Science Fiction'), ('F.Y.Engineering', 'F.Y.Engineering'), ('S.Y.Engineering', 'S.Y.Engineering'), ('Horror', 'Horror'), ('other', 'other'), ('Comic', 'Comic')], default='other', max_length=120),
        ),
    ]
